"""Measured, deterministic reports. Orchestrates generation, detection, then scoring."""

import json
from pathlib import Path

from .detect import detect, query
from .evaluate import evaluate
from .generate import generate, validate_clean
from .inject import inject
from .model import CATEGORIES

# Declared before scoring; different data/placement seeds, same defect mechanisms.
DEVELOPMENT_SEED = 17
HELD_OUT_SEEDS = (101, 202, 303)
SCENARIOS = ("sparse", "standard", "stress")


def dollars(cents):
    return f"${cents / 100:,.2f}"


def build_report(out):
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    clean = generate(DEVELOPMENT_SEED)
    validate_clean(clean)
    baseline_flags = detect(clean)
    assert not baseline_flags, "Clean baseline failed SQL checks"
    analytics = query(clean, "analytics.sql")[0]
    business = query(clean, "business_summary.sql")
    runs = []
    for seed in (DEVELOPMENT_SEED,) + HELD_OUT_SEEDS:
        baseline = generate(seed)
        validate_clean(baseline)
        clean_result = evaluate(detect(baseline), {"expected_flags": []})
        runs.append(
            dict(
                seed=seed,
                scenario="clean",
                split="development" if seed == DEVELOPMENT_SEED else "held_out_seed",
                **clean_result,
            )
        )
        for scenario in SCENARIOS:
            dirty, manifest = inject(baseline, seed, scenario)
            flags = detect(dirty)  # Labels first become an input only AFTER detection.
            runs.append(
                dict(
                    seed=seed,
                    scenario=scenario,
                    split="development" if seed == DEVELOPMENT_SEED else "held_out_seed",
                    check_flags=len(flags),
                    labeled_units=len(manifest["expected_flags"]),
                    **evaluate(flags, manifest),
                )
            )
    failures = [run for run in runs if run["false_positives"] or run["false_negatives"]]
    if failures:
        raise ValueError("Evaluation drift: refusing to publish a passing report; inspect detection/tests")
    aggregates = []
    for category in CATEGORIES:
        rows = [m for run in runs for m in run["metrics"] if m["category"] == category]
        tp, fp, fn = (sum(r[k] for r in rows) for k in ("tp", "fp", "fn"))
        aggregates.append(
            dict(
                category=category,
                tp=tp,
                fp=fp,
                fn=fn,
                precision=tp / (tp + fp) if tp + fp else None,
                recall=tp / (tp + fn) if tp + fn else None,
            )
        )
    payload = dict(
        development_seed=DEVELOPMENT_SEED,
        held_out_seeds=HELD_OUT_SEEDS,
        row_counts={t: len(r) for t, r in clean.items()},
        analytics=analytics,
        business_summary=business,
        aggregate_metrics=aggregates,
        runs=runs,
    )
    (out / "results.json").write_text(json.dumps(payload, indent=2) + "\n")
    pct = analytics["overstatement_cents"] / analytics["correct_header_paid_cents"] * 100
    lines = [
        "# Measured release 1 results",
        "",
        "Generated by `PYTHONPATH=src python -m claims_quality report --out reports`. All dollars below are synthetic USD-equivalent illustration, stored as integer cents.",
        "",
        "## Business finding",
        "",
        f"On development seed {DEVELOPMENT_SEED}, summing header payments after joining to claim lines reports **{dollars(analytics['incorrect_join_paid_cents'])}**, while the reconciled payment total is **{dollars(analytics['correct_header_paid_cents'])}**. The join overstates payments by **{dollars(analytics['overstatement_cents'])} ({pct:.2f}%)**.",
        "",
        "The correction sums at header grain, sums line payments, or aggregates lines to one row per claim before joining. All three totals agree. Comparing the incorrect result with the independent line ledger catches the error. `SUM(DISTINCT paid_cents)` is not a correction: separate claims can share a dollar amount.",
        "",
        "**Recommended analyst action:** establish the reporting grain and reconciliation checks before publishing payment totals. Route quality flags for source investigation; this project does not silently delete records, recover money, identify fraud, or adjudicate services.",
        "",
        "## Clean baseline",
        "",
        "| Table | Rows |",
        "|---|---:|",
    ]
    lines.extend(f"| {t} | {len(r)} |" for t, r in clean.items())
    lines += [
        "",
        "All four clean seeds pass independent Python invariants and produce zero SQL flags. Included lookalikes are structurally consistent under this synthetic contract; their clinical or billing legitimacy is unknown.",
        "",
        "## Controlled evaluation",
        "",
        "Unit: one **category × table × physical record_id**. Multiple checks in a category collapse to one unit. Every occurrence of an exact duplicate is positive, including the original. A propagated header financial failure is also a positive when a line error breaks its totals.",
        "",
        "| Category | TP | FP | FN | Precision | Recall |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for m in aggregates:
        lines.append(
            f"| {m['category']} | {m['tp']} | {m['fp']} | {m['fn']} | {m['precision']:.3f} | {m['recall']:.3f} |"
        )
    lines += [
        "",
        "Aggregates pool four seeds × three dirty scenarios, plus four clean runs. Development seed: 17. Held-out data/placement seeds: 101, 202, 303. Each scenario is scored separately in `results.json`; none failed. These are repeated controlled mechanisms, **not unseen defect types, real claims accuracy, or an external validation set**. No prevalence-based accuracy or clinical performance is claimed.",
        "",
        "| Scenario, per seed | Duplicate units | FK units | Date units | Financial units |",
        "|---|---:|---:|---:|---:|",
        "| sparse | 2 | 1 | 1 | 1 |",
        "| standard | 4 | 2 | 2 | 2 |",
        "| stress | 6 | 3 | 3 | 5 |",
        "",
        "Clean-run precision and recall are `null` (undefined) because their denominators are zero; they are not reported as 100%. Stress includes three header payment errors plus one line payment error that flags both line and header. Event counts therefore differ from row/category counts.",
        "",
        "## Illustrative provider summary",
        "",
        "| Synthetic provider type | Claims | Distinct members | Paid | Patient | Mean receipt-to-payment days |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    lines.extend(
        f"| {r['provider_type']} | {r['claim_count']} | {r['distinct_members']} | {dollars(r['paid_cents'])} | {dollars(r['patient_cents'])} | {r['mean_receipt_to_payment_days']} |"
        for r in business
    )
    lines += [
        "",
        "Provider-group member counts are not additive across groups. The date lag is fixed by fixture design, so it provides no evidence about operational performance. No provider comparison or recommendation is warranted from this generated sample.",
        "",
        "## Limits",
        "",
        "See docs/LIMITATIONS.md in the source repository. Checks encode an explicit simplified data contract. The data omit reversals, adjustments, coordination of benefits, claim lifecycle revisions, coding standards, missing values and external formats. Controlled perfect scores show implementation agreement with the fixtures, not production readiness.",
        "",
    ]
    (out / "RESULTS.md").write_text("\n".join(lines))
